import type { Trail, Topic, Question } from '../types'

export const trails: Trail[] = [
  {
    id: 'trail-classes-palavras',
    nome: 'Classes de Palavras',
    materia: 'Língua Portuguesa',
    ano_escolar: 5,
    narrativa: 'Uma jornada pelo universo das palavras — descubra os poderes secretos de cada classe e como elas constroem o mundo ao seu redor.',
    topicos: ['topic-substantivo', 'topic-adjetivo'],
  },
]

export const topics: Topic[] = [
  {
    id: 'topic-substantivo',
    nome: 'Substantivo',
    trilha_id: 'trail-classes-palavras',
    eixo_bncc: 'Análise linguística e gramática',
    gancho_curiosidade: 'Você sabia que tudo que existe tem um nome — e esse nome é uma palavra especial? Por que será que "amor" e "saudade" são substantivos, mas "feliz" não é?',
    pre_requisitos: [],
    itens: [
      'q-sub-01', 'q-sub-02', 'q-sub-03', 'q-sub-04',
      'q-sub-05', 'q-sub-06', 'q-sub-07', 'q-sub-08',
    ],
  },
  {
    id: 'topic-adjetivo',
    nome: 'Adjetivo',
    trilha_id: 'trail-classes-palavras',
    eixo_bncc: 'Análise linguística e gramática',
    gancho_curiosidade: 'Imagine um jogo sem adjetivos: sem "raro", sem "épico", sem "lendário". Chato, né? Descubra por que os adjetivos são o "farmador de aura" das frases.',
    pre_requisitos: ['topic-substantivo'],
    itens: [
      'q-adj-01', 'q-adj-02', 'q-adj-03', 'q-adj-04',
      'q-adj-05', 'q-adj-06', 'q-adj-07', 'q-adj-08',
    ],
  },
]

export const questions: Question[] = [
  // ── SUBSTANTIVO ────────────────────────────────────────────────────────────
  {
    id: 'q-sub-01',
    topico_id: 'topic-substantivo',
    tipo: 'multipla_escolha',
    dificuldade: 1,
    enunciado: 'Qual das palavras abaixo é um substantivo?',
    resposta_correta: 'cidade',
    distratores: ['correr', 'bonito', 'rapidamente'],
    explicacao: 'Substantivo é a palavra que dá nome a seres, lugares, sentimentos e coisas. "Cidade" é o nome de um lugar — portanto é substantivo.',
  },
  {
    id: 'q-sub-02',
    topico_id: 'topic-substantivo',
    tipo: 'multipla_escolha',
    dificuldade: 1,
    enunciado: '"Saudade" é um substantivo? Por quê?',
    resposta_correta: 'Sim — é o nome de um sentimento',
    distratores: [
      'Não — sentimentos não são substantivos',
      'Sim — porque termina em "ade"',
      'Não — é um verbo disfarçado',
    ],
    explicacao: 'Substantivos nomeiam não só objetos físicos, mas também sentimentos e estados. "Saudade" é o nome de um sentimento, portanto é substantivo.',
  },
  {
    id: 'q-sub-03',
    topico_id: 'topic-substantivo',
    tipo: 'lacuna',
    dificuldade: 1,
    enunciado: 'Substantivo próprio tem a primeira letra em maiúscula e nomeia um ser _______ (único/geral).',
    resposta_correta: 'único',
    explicacao: 'Substantivos próprios identificam um ser específico e único — como "Brasil", "Maria" ou "Amazônia". Por isso começam com maiúscula.',
  },
  {
    id: 'q-sub-04',
    topico_id: 'topic-substantivo',
    tipo: 'multipla_escolha',
    dificuldade: 2,
    enunciado: 'Na frase "O time ganhou o jogo", quantos substantivos existem?',
    resposta_correta: '2 — time e jogo',
    distratores: ['1 — só jogo', '3 — time, ganhou e jogo', '0 — não há substantivos'],
    explicacao: '"Time" e "jogo" são substantivos — nomeiam coisas. "Ganhou" é verbo (ação) e "o" é artigo.',
  },
  {
    id: 'q-sub-05',
    topico_id: 'topic-substantivo',
    tipo: 'verdadeiro_falso',
    dificuldade: 2,
    enunciado: '"Beleza" e "coragem" são substantivos abstratos porque não podemos tocar neles.',
    resposta_correta: 'Verdadeiro',
    explicacao: 'Substantivos abstratos nomeiam ideias, qualidades e sentimentos que não têm existência física — como beleza, coragem, amor e liberdade.',
  },
  {
    id: 'q-sub-06',
    topico_id: 'topic-substantivo',
    tipo: 'multipla_escolha',
    dificuldade: 2,
    enunciado: 'Qual é o plural correto de "cidadão"?',
    resposta_correta: 'cidadãos',
    distratores: ['cidadões', 'cidadães', 'cidadãos e cidadões são os dois corretos'],
    explicacao: 'A maioria dos substantivos terminados em "-ão" fazem plural em "-ãos": cidadão → cidadãos. Outros casos: leão → leões, alemão → alemães.',
  },
  {
    id: 'q-sub-07',
    topico_id: 'topic-substantivo',
    tipo: 'ordenacao',
    dificuldade: 2,
    enunciado: 'Separe as palavras em dois grupos: SUBSTANTIVOS e NÃO SUBSTANTIVOS.\nPalavras: escola | estudar | felicidade | verde | cachorro | correr',
    resposta_correta: 'Substantivos: escola, felicidade, cachorro | Não substantivos: estudar, verde, correr',
    explicacao: '"Escola", "felicidade" e "cachorro" nomeiam um lugar, um sentimento e um animal — são substantivos. "Estudar" e "correr" são verbos; "verde" é adjetivo.',
  },
  {
    id: 'q-sub-08',
    topico_id: 'topic-substantivo',
    tipo: 'elaboracao',
    dificuldade: 3,
    enunciado: 'Escreva com suas próprias palavras: o que é um substantivo? Tente dar um exemplo que você inventou — pode ser de um jogo, série ou coisa que você gosta.',
    resposta_correta: '',
    explicacao: 'Não existe uma única resposta certa aqui. O importante é que você tenha explicado com suas palavras o que é um substantivo e dado um exemplo real para você.',
    referencia_cultural: 'exemplo livre da criança',
  },

  // ── ADJETIVO ───────────────────────────────────────────────────────────────
  {
    id: 'q-adj-01',
    topico_id: 'topic-adjetivo',
    tipo: 'multipla_escolha',
    dificuldade: 1,
    enunciado: 'Qual das palavras abaixo é um adjetivo?',
    resposta_correta: 'corajoso',
    distratores: ['coragem', 'correr', 'rapidamente'],
    explicacao: 'Adjetivo é a palavra que caracteriza ou qualifica um substantivo. "Corajoso" descreve uma característica de alguém — portanto é adjetivo.',
  },
  {
    id: 'q-adj-02',
    topico_id: 'topic-adjetivo',
    tipo: 'multipla_escolha',
    dificuldade: 1,
    enunciado: 'No jogo, você encontrou uma espada "lendária". Nessa frase, "lendária" é:',
    resposta_correta: 'Adjetivo — qualifica a espada',
    distratores: [
      'Substantivo — é o nome da espada',
      'Verbo — indica uma ação',
      'Advérbio — indica modo',
    ],
    explicacao: '"Lendária" descreve como é a espada. Sempre que uma palavra qualifica (descreve) um substantivo, ela é adjetivo.',
    referencia_cultural: 'item lendário de RPG/jogo',
    validade_cultural: '2028-01-01',
  },
  {
    id: 'q-adj-03',
    topico_id: 'topic-adjetivo',
    tipo: 'lacuna',
    dificuldade: 1,
    enunciado: 'O adjetivo concorda em gênero e número com o _______ que ele qualifica.',
    resposta_correta: 'substantivo',
    explicacao: 'O adjetivo "segue" o substantivo: se o substantivo é feminino plural, o adjetivo também fica feminino plural. Ex: "meninas inteligentes".',
  },
  {
    id: 'q-adj-04',
    topico_id: 'topic-adjetivo',
    tipo: 'multipla_escolha',
    dificuldade: 2,
    enunciado: 'Seu personagem está "farmando aura" — ou seja, está ficando cada vez mais respeitado. Qual adjetivo melhor descreve alguém com muita aura?',
    resposta_correta: 'imponente',
    distratores: ['apressado', 'distraído', 'desorganizado'],
    explicacao: '"Imponente" descreve alguém que transmite respeito e presença. É um adjetivo que qualifica a pessoa — exatamente o que acontece com quem está "farmando aura".',
    referencia_cultural: 'farmando aura',
    validade_cultural: '2027-01-01',
  },
  {
    id: 'q-adj-05',
    topico_id: 'topic-adjetivo',
    tipo: 'verdadeiro_falso',
    dificuldade: 2,
    enunciado: 'Na frase "A menina inteligente resolveu o problema difícil", há dois adjetivos.',
    resposta_correta: 'Verdadeiro',
    explicacao: '"Inteligente" qualifica "menina" e "difícil" qualifica "problema" — dois adjetivos na mesma frase.',
  },
  {
    id: 'q-adj-06',
    topico_id: 'topic-adjetivo',
    tipo: 'multipla_escolha',
    dificuldade: 2,
    enunciado: 'Qual é o feminino correto de "trabalhador"?',
    resposta_correta: 'trabalhadora',
    distratores: ['trabalhadeira', 'trabalhadora e trabalhadriz são os dois corretos', 'trabalhadoresa'],
    explicacao: 'Adjetivos terminados em "-or" normalmente formam o feminino com "-ora": trabalhador → trabalhadora, protetor → protetora.',
  },
  {
    id: 'q-adj-07',
    topico_id: 'topic-adjetivo',
    tipo: 'ordenacao',
    dificuldade: 2,
    enunciado: 'Separe em ADJETIVOS e NÃO ADJETIVOS:\nfantástico | correr | engraçada | escola | péssimo | liberdade | alto',
    resposta_correta: 'Adjetivos: fantástico, engraçada, péssimo, alto | Não adjetivos: correr, escola, liberdade',
    explicacao: '"Fantástico", "engraçada", "péssimo" e "alto" qualificam substantivos — são adjetivos. "Correr" é verbo; "escola" e "liberdade" são substantivos.',
  },
  {
    id: 'q-adj-08',
    topico_id: 'topic-adjetivo',
    tipo: 'elaboracao',
    dificuldade: 3,
    enunciado: 'Pense no seu personagem favorito de um jogo, série ou livro. Use pelo menos 3 adjetivos para descrevê-lo e explique por que cada um combina com ele.',
    resposta_correta: '',
    explicacao: 'Não existe resposta única. O importante é ter usado adjetivos reais e explicado como cada um descreve o personagem.',
    referencia_cultural: 'personagem favorito da criança',
  },
]
